// <auto-generated />
using System;
using GestaoResiduos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoResiduos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260917042337_DadosIniciais")]
    partial class DadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoResiduos.Models.Coleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoResiduoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoResiduoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Coletas");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Processamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColetaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Eficiencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QuantidadeProcessada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoResiduoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId")
                        .IsUnique();

                    b.HasIndex("TipoResiduoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Processamentos");
                });

            modelBuilder.Entity("GestaoResiduos.Models.TipoResiduo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorIdentificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoProcessamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reciclavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TaxaReciclagem")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TipoResiduos");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Coleta", b =>
                {
                    b.HasOne("GestaoResiduos.Models.TipoResiduo", "TipoResiduo")
                        .WithMany("Coletas")
                        .HasForeignKey("TipoResiduoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoResiduos.Models.Usuario", "Usuario")
                        .WithMany("Coletas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoResiduo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Processamento", b =>
                {
                    b.HasOne("GestaoResiduos.Models.Coleta", "Coleta")
                        .WithOne("Processamento")
                        .HasForeignKey("GestaoResiduos.Models.Processamento", "ColetaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoResiduos.Models.TipoResiduo", "TipoResiduo")
                        .WithMany("Processamentos")
                        .HasForeignKey("TipoResiduoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestaoResiduos.Models.Usuario", "Usuario")
                        .WithMany("Processamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coleta");

                    b.Navigation("TipoResiduo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Coleta", b =>
                {
                    b.Navigation("Processamento");
                });

            modelBuilder.Entity("GestaoResiduos.Models.TipoResiduo", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Processamentos");
                });

            modelBuilder.Entity("GestaoResiduos.Models.Usuario", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Processamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
